import React from 'react';
import { Info, Code2, Server, Database, BrainCircuit, ShieldAlert, FileText } from 'lucide-react';

export default function AboutProject() {
  return (
    <div className="page-container animate-fade-in">
      <div style={{ textAlign: 'center', marginBottom: '2.5rem' }}>
        <div className="badge badge-teal" style={{ marginBottom: '0.5rem' }}>
          <Info size={14} /> Documentation & Metadata
        </div>
        <h1 style={{ fontSize: '2rem', fontWeight: 800, color: '#ffffff' }}>
          About Pattern Recognition Project
        </h1>
        <p style={{ fontSize: '0.9375rem', color: '#9ca3af', maxWidth: '700px', margin: '0.5rem auto 0 auto' }}>
          Academic Pattern Recognition project demonstrating end-to-end Machine Learning pipeline design, feature scaling, model comparison, and real-time clinical prediction.
        </p>
      </div>

      {/* Mandatory Disclaimer Box */}
      <div className="glass-card" style={{
        background: 'linear-gradient(135deg, rgba(245, 158, 11, 0.15) 0%, rgba(15, 23, 42, 0.9) 100%)',
        border: '1px solid rgba(245, 158, 11, 0.4)',
        padding: '1.75rem',
        marginBottom: '2.5rem'
      }}>
        <div style={{ display: 'flex', gap: '1rem', alignItems: 'flex-start' }}>
          <ShieldAlert size={28} color="#f59e0b" style={{ flexShrink: 0 }} />
          <div>
            <h3 style={{ fontSize: '1.125rem', fontWeight: 700, color: '#fef3c7', marginBottom: '0.375rem' }}>
              Official Academic Disclaimer
            </h3>
            <p style={{ fontSize: '0.875rem', color: '#fef3c7', lineHeight: 1.6 }}>
              This project is developed for academic and educational purposes only. It is not a medical diagnostic tool. Predictions generated by machine learning models in this system should not be used as a substitute for professional medical advice, diagnosis, or clinical decisions.
            </p>
          </div>
        </div>
      </div>

      {/* Tech Stack Cards */}
      <h2 style={{ fontSize: '1.375rem', fontWeight: 700, color: '#ffffff', marginBottom: '1.25rem' }}>
        System Architecture & Technology Stack
      </h2>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '1.25rem', marginBottom: '3rem' }}>
        
        <div className="glass-card">
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.75rem' }}>
            <div style={{ padding: '0.5rem', borderRadius: '8px', background: 'rgba(20, 184, 166, 0.15)' }}>
              <Code2 size={20} color="#14b8a6" />
            </div>
            <h3 style={{ fontSize: '1rem', fontWeight: 700, color: '#ffffff' }}>Frontend Stack</h3>
          </div>
          <ul style={{ fontSize: '0.8125rem', color: '#9ca3af', lineHeight: 1.7, paddingLeft: '1.25rem' }}>
            <li>React.js (Vite Build Tool)</li>
            <li>Recharts Data Visualization</li>
            <li>Lucide React Icon System</li>
            <li>Responsive Glassmorphic UI</li>
          </ul>
        </div>

        <div className="glass-card">
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.75rem' }}>
            <div style={{ padding: '0.5rem', borderRadius: '8px', background: 'rgba(99, 102, 241, 0.15)' }}>
              <Server size={20} color="#6366f1" />
            </div>
            <h3 style={{ fontSize: '1rem', fontWeight: 700, color: '#ffffff' }}>Backend REST API</h3>
          </div>
          <ul style={{ fontSize: '0.8125rem', color: '#9ca3af', lineHeight: 1.7, paddingLeft: '1.25rem' }}>
            <li>Python 3.12 + Flask Framework</li>
            <li>Flask-CORS Middleware</li>
            <li>Joblib Model Serialization</li>
            <li>Pytest Automated Testing</li>
          </ul>
        </div>

        <div className="glass-card">
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.75rem' }}>
            <div style={{ padding: '0.5rem', borderRadius: '8px', background: 'rgba(16, 185, 129, 0.15)' }}>
              <BrainCircuit size={20} color="#10b981" />
            </div>
            <h3 style={{ fontSize: '1rem', fontWeight: 700, color: '#ffffff' }}>Machine Learning Engine</h3>
          </div>
          <ul style={{ fontSize: '0.8125rem', color: '#9ca3af', lineHeight: 1.7, paddingLeft: '1.25rem' }}>
            <li>Scikit-Learn (LR, KNN, DT, SVM)</li>
            <li>StandardScaler Preprocessing</li>
            <li>SimpleImputer (Median zero handling)</li>
            <li>Pandas & NumPy Data Pipeline</li>
          </ul>
        </div>

      </div>

      {/* API Endpoints Reference */}
      <div className="glass-card">
        <h3 style={{ fontSize: '1.125rem', fontWeight: 700, color: '#ffffff', marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          <FileText size={18} color="#14b8a6" /> REST API Endpoint Reference
        </h3>
        <div style={{ overflowX: 'auto' }}>
          <table className="custom-table" style={{ fontSize: '0.8125rem' }}>
            <thead>
              <tr>
                <th>Method</th>
                <th>Endpoint</th>
                <th>Description</th>
                <th>Response</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><span className="badge badge-emerald" style={{ fontSize: '0.6875rem' }}>GET</span></td>
                <td><code>/api/health</code></td>
                <td>Backend service status check</td>
                <td>Status JSON</td>
              </tr>
              <tr>
                <td><span className="badge badge-emerald" style={{ fontSize: '0.6875rem' }}>GET</span></td>
                <td><code>/api/dataset-summary</code></td>
                <td>Dataset metrics, zero counts & stats</td>
                <td>Summary JSON</td>
              </tr>
              <tr>
                <td><span className="badge badge-emerald" style={{ fontSize: '0.6875rem' }}>GET</span></td>
                <td><code>/api/performance</code></td>
                <td>Calculated Accuracy, Precision, Recall, F1</td>
                <td>Models JSON</td>
              </tr>
              <tr>
                <td><span className="badge badge-emerald" style={{ fontSize: '0.6875rem' }}>GET</span></td>
                <td><code>/api/confusion-matrix/&lt;model&gt;</code></td>
                <td>2x2 Matrix (TN, FP, FN, TP) for specified model</td>
                <td>Matrix JSON</td>
              </tr>
              <tr>
                <td><span className="badge badge-indigo" style={{ fontSize: '0.6875rem' }}>POST</span></td>
                <td><code>/api/predict</code></td>
                <td>StandardScaler preprocess & model inference</td>
                <td>Prediction JSON</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
